/**
 * Task System Mock Data
 *
 * Provides realistic mock data for the AI-powered task system.
 * Demonstrates how tasks continue from previous days.
 */

import type {
  Task,
  DailyPlan,
  WeeklyPlan,
  TaskStats,
  TaskCategory,
  TaskPriority,
  TaskStatus,
} from "../types";

// ============================================
// Helper Functions
// ============================================

const today = "2026-07-28"; // Fixed date for hydration safety
const yesterday = "2026-07-27";
const tomorrow = "2026-07-29";

function createTask(overrides: Partial<Task>): Task {
  return {
    id: crypto.randomUUID(),
    title: "Untitled Task",
    category: "other",
    priority: "medium",
    status: "pending",
    source: "user-created",
    estimatedMinutes: 30,
    progress: 0,
    scheduledDate: today,
    tags: [],
    createdAt: "2026-07-28T00:00:00.000Z",
    updatedAt: "2026-07-28T00:00:00.000Z",
    ...overrides,
  };
}

// ============================================
// Mock Tasks
// ============================================

// Tasks are now dynamically generated by AI when user clicks Generate
// No hardcoded initial tasks - progressive difficulty is handled in use-tasks.ts

// ============================================
// Mock Daily Plan
// ============================================

export const mockDailyPlan: DailyPlan = {
  date: today,
  tasks: [],
  totalTasks: 0,
  completedTasks: 0,
  totalEstimatedMinutes: 0,
  totalActualMinutes: 0,
  focusScore: 0,
  categories: [],
};

// ============================================
// Mock Weekly Plan
// ============================================

export const mockWeeklyPlan: WeeklyPlan = {
  startDate: "2026-07-25",
  endDate: "2026-07-31",
  dailyPlans: [
    {
      date: "2026-07-25",
      tasks: [],
      totalTasks: 0,
      completedTasks: 0,
      totalEstimatedMinutes: 0,
      totalActualMinutes: 0,
      focusScore: 0,
      categories: [],
    },
    {
      date: "2026-07-26",
      tasks: [],
      totalTasks: 0,
      completedTasks: 0,
      totalEstimatedMinutes: 0,
      totalActualMinutes: 0,
      focusScore: 0,
      categories: [],
    },
    {
      date: yesterday,
      tasks: [],
      totalTasks: 0,
      completedTasks: 0,
      totalEstimatedMinutes: 0,
      totalActualMinutes: 0,
      focusScore: 0,
      categories: [],
    },
    {
      date: today,
      tasks: mockDailyPlan.tasks,
      totalTasks: mockDailyPlan.totalTasks,
      completedTasks: mockDailyPlan.completedTasks,
      totalEstimatedMinutes: mockDailyPlan.totalEstimatedMinutes,
      totalActualMinutes: mockDailyPlan.totalActualMinutes,
      focusScore: mockDailyPlan.focusScore,
      categories: mockDailyPlan.categories,
    },
  ],
  totalTasks: 0,
  completedTasks: 0,
  streakDays: 0,
  weeklyGoal: 25,
  progress: 0,
  insights: [],
};

// ============================================
// Mock Task Statistics
// ============================================

export const mockTaskStats: TaskStats = {
  totalTasks: 0,
  completedTasks: 0,
  completionRate: 0,

  totalEstimatedMinutes: 0,
  totalActualMinutes: 0,
  timeAccuracy: 0,

  currentStreak: 0,
  longestStreak: 0,
  streakGoal: 30,

  categoryBreakdown: [],

  dailyStats: Array.from({ length: 7 }, (_, i) => ({
    date: `2026-07-${22 + i}`,
    tasksCompleted: 0,
    minutesWorked: 0,
    focusScore: 0,
  })),

  weeklyTrend: 0,

  averageFocusScore: 0,
  mostProductiveTimeOfDay: "morning" as const,
  mostProductiveDayOfWeek: "Tuesday",
};
